
#!/usr/bin/expect -f
set timeout 30
spawn qemu-system-riscv32 -M virt -bios /home/bhanuharya/Documents/buildroot-2024.02.10/output/images/fw_jump.elf                           -kernel /home/bhanuharya/Documents/buildroot-2024.02.10/output/images/Image                           -append "rootwait root=/dev/vda ro"                           -drive file=/home/bhanuharya/Documents/buildroot-2024.02.10/output/images/rootfs.ext2,format=raw,id=hd0                           -device virtio-blk-device,drive=hd0 -nographic -serial mon:stdio
expect "buildroot login: "
send "root\r"
expect "# "
send "cd /\r"
expect "# "
send "time ./a.riscv\r"
expect "# "
send "poweroff\r"
expect eof
